// Code generated by capnpc-go. DO NOT EDIT.

package crossXDT

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
	fmt "fmt"
)

type StreamData capnp.Client

// StreamData_TypeID is the unique identifier for the type StreamData.
const StreamData_TypeID = 0xc7110414b2c7b8e7

func (c StreamData) ServeData(ctx context.Context, params func(StreamData_serveData_Params) error) (StreamData_serveData_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xc7110414b2c7b8e7,
			MethodID:      0,
			InterfaceName: "proto/crossXDT.capnp:StreamData",
			MethodName:    "serveData",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(StreamData_serveData_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return StreamData_serveData_Results_Future{Future: ans.Future()}, release
}
func (c StreamData) ServeBroadcastData(ctx context.Context, params func(StreamData_serveBroadcastData_Params) error) (StreamData_serveBroadcastData_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xc7110414b2c7b8e7,
			MethodID:      1,
			InterfaceName: "proto/crossXDT.capnp:StreamData",
			MethodName:    "serveBroadcastData",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(StreamData_serveBroadcastData_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return StreamData_serveBroadcastData_Results_Future{Future: ans.Future()}, release
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c StreamData) String() string {
	return fmt.Sprintf("%T(%v)", c, capnp.Client(c))
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c StreamData) AddRef() StreamData {
	return StreamData(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c StreamData) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c StreamData) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c StreamData) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (StreamData) DecodeFromPtr(p capnp.Ptr) StreamData {
	return StreamData(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c StreamData) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c StreamData) IsSame(other StreamData) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c StreamData) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c StreamData) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
} // A StreamData_Server is a StreamData with a local implementation.
type StreamData_Server interface {
	ServeData(context.Context, StreamData_serveData) error

	ServeBroadcastData(context.Context, StreamData_serveBroadcastData) error
}

// StreamData_NewServer creates a new Server from an implementation of StreamData_Server.
func StreamData_NewServer(s StreamData_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(StreamData_Methods(nil, s), s, c)
}

// StreamData_ServerToClient creates a new Client from an implementation of StreamData_Server.
// The caller is responsible for calling Release on the returned Client.
func StreamData_ServerToClient(s StreamData_Server) StreamData {
	return StreamData(capnp.NewClient(StreamData_NewServer(s)))
}

// StreamData_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func StreamData_Methods(methods []server.Method, s StreamData_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc7110414b2c7b8e7,
			MethodID:      0,
			InterfaceName: "proto/crossXDT.capnp:StreamData",
			MethodName:    "serveData",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.ServeData(ctx, StreamData_serveData{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc7110414b2c7b8e7,
			MethodID:      1,
			InterfaceName: "proto/crossXDT.capnp:StreamData",
			MethodName:    "serveBroadcastData",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.ServeBroadcastData(ctx, StreamData_serveBroadcastData{call})
		},
	})

	return methods
}

// StreamData_serveData holds the state for a server call to StreamData.serveData.
// See server.Call for documentation.
type StreamData_serveData struct {
	*server.Call
}

// Args returns the call's arguments.
func (c StreamData_serveData) Args() StreamData_serveData_Params {
	return StreamData_serveData_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c StreamData_serveData) AllocResults() (StreamData_serveData_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StreamData_serveData_Results(r), err
}

// StreamData_serveBroadcastData holds the state for a server call to StreamData.serveBroadcastData.
// See server.Call for documentation.
type StreamData_serveBroadcastData struct {
	*server.Call
}

// Args returns the call's arguments.
func (c StreamData_serveBroadcastData) Args() StreamData_serveBroadcastData_Params {
	return StreamData_serveBroadcastData_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c StreamData_serveBroadcastData) AllocResults() (StreamData_serveBroadcastData_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StreamData_serveBroadcastData_Results(r), err
}

// StreamData_List is a list of StreamData.
type StreamData_List = capnp.CapList[StreamData]

// NewStreamData creates a new list of StreamData.
func NewStreamData_List(s *capnp.Segment, sz int32) (StreamData_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[StreamData](l), err
}

type StreamData_serveData_Params capnp.Struct

// StreamData_serveData_Params_TypeID is the unique identifier for the type StreamData_serveData_Params.
const StreamData_serveData_Params_TypeID = 0x8bd2aaf08016a52a

func NewStreamData_serveData_Params(s *capnp.Segment) (StreamData_serveData_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StreamData_serveData_Params(st), err
}

func NewRootStreamData_serveData_Params(s *capnp.Segment) (StreamData_serveData_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StreamData_serveData_Params(st), err
}

func ReadRootStreamData_serveData_Params(msg *capnp.Message) (StreamData_serveData_Params, error) {
	root, err := msg.Root()
	return StreamData_serveData_Params(root.Struct()), err
}

func (s StreamData_serveData_Params) String() string {
	str, _ := text.Marshal(0x8bd2aaf08016a52a, capnp.Struct(s))
	return str
}

func (s StreamData_serveData_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StreamData_serveData_Params) DecodeFromPtr(p capnp.Ptr) StreamData_serveData_Params {
	return StreamData_serveData_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StreamData_serveData_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StreamData_serveData_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StreamData_serveData_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StreamData_serveData_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s StreamData_serveData_Params) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s StreamData_serveData_Params) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s StreamData_serveData_Params) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s StreamData_serveData_Params) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// StreamData_serveData_Params_List is a list of StreamData_serveData_Params.
type StreamData_serveData_Params_List = capnp.StructList[StreamData_serveData_Params]

// NewStreamData_serveData_Params creates a new list of StreamData_serveData_Params.
func NewStreamData_serveData_Params_List(s *capnp.Segment, sz int32) (StreamData_serveData_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[StreamData_serveData_Params](l), err
}

// StreamData_serveData_Params_Future is a wrapper for a StreamData_serveData_Params promised by a client call.
type StreamData_serveData_Params_Future struct{ *capnp.Future }

func (f StreamData_serveData_Params_Future) Struct() (StreamData_serveData_Params, error) {
	p, err := f.Future.Ptr()
	return StreamData_serveData_Params(p.Struct()), err
}

type StreamData_serveData_Results capnp.Struct

// StreamData_serveData_Results_TypeID is the unique identifier for the type StreamData_serveData_Results.
const StreamData_serveData_Results_TypeID = 0x8b36f15eba05c6d8

func NewStreamData_serveData_Results(s *capnp.Segment) (StreamData_serveData_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StreamData_serveData_Results(st), err
}

func NewRootStreamData_serveData_Results(s *capnp.Segment) (StreamData_serveData_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StreamData_serveData_Results(st), err
}

func ReadRootStreamData_serveData_Results(msg *capnp.Message) (StreamData_serveData_Results, error) {
	root, err := msg.Root()
	return StreamData_serveData_Results(root.Struct()), err
}

func (s StreamData_serveData_Results) String() string {
	str, _ := text.Marshal(0x8b36f15eba05c6d8, capnp.Struct(s))
	return str
}

func (s StreamData_serveData_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StreamData_serveData_Results) DecodeFromPtr(p capnp.Ptr) StreamData_serveData_Results {
	return StreamData_serveData_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StreamData_serveData_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StreamData_serveData_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StreamData_serveData_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StreamData_serveData_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s StreamData_serveData_Results) Payload() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s StreamData_serveData_Results) HasPayload() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s StreamData_serveData_Results) SetPayload(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// StreamData_serveData_Results_List is a list of StreamData_serveData_Results.
type StreamData_serveData_Results_List = capnp.StructList[StreamData_serveData_Results]

// NewStreamData_serveData_Results creates a new list of StreamData_serveData_Results.
func NewStreamData_serveData_Results_List(s *capnp.Segment, sz int32) (StreamData_serveData_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[StreamData_serveData_Results](l), err
}

// StreamData_serveData_Results_Future is a wrapper for a StreamData_serveData_Results promised by a client call.
type StreamData_serveData_Results_Future struct{ *capnp.Future }

func (f StreamData_serveData_Results_Future) Struct() (StreamData_serveData_Results, error) {
	p, err := f.Future.Ptr()
	return StreamData_serveData_Results(p.Struct()), err
}

type StreamData_serveBroadcastData_Params capnp.Struct

// StreamData_serveBroadcastData_Params_TypeID is the unique identifier for the type StreamData_serveBroadcastData_Params.
const StreamData_serveBroadcastData_Params_TypeID = 0xa4ddd6b9c74ee513

func NewStreamData_serveBroadcastData_Params(s *capnp.Segment) (StreamData_serveBroadcastData_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StreamData_serveBroadcastData_Params(st), err
}

func NewRootStreamData_serveBroadcastData_Params(s *capnp.Segment) (StreamData_serveBroadcastData_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StreamData_serveBroadcastData_Params(st), err
}

func ReadRootStreamData_serveBroadcastData_Params(msg *capnp.Message) (StreamData_serveBroadcastData_Params, error) {
	root, err := msg.Root()
	return StreamData_serveBroadcastData_Params(root.Struct()), err
}

func (s StreamData_serveBroadcastData_Params) String() string {
	str, _ := text.Marshal(0xa4ddd6b9c74ee513, capnp.Struct(s))
	return str
}

func (s StreamData_serveBroadcastData_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StreamData_serveBroadcastData_Params) DecodeFromPtr(p capnp.Ptr) StreamData_serveBroadcastData_Params {
	return StreamData_serveBroadcastData_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StreamData_serveBroadcastData_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StreamData_serveBroadcastData_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StreamData_serveBroadcastData_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StreamData_serveBroadcastData_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s StreamData_serveBroadcastData_Params) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s StreamData_serveBroadcastData_Params) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s StreamData_serveBroadcastData_Params) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s StreamData_serveBroadcastData_Params) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// StreamData_serveBroadcastData_Params_List is a list of StreamData_serveBroadcastData_Params.
type StreamData_serveBroadcastData_Params_List = capnp.StructList[StreamData_serveBroadcastData_Params]

// NewStreamData_serveBroadcastData_Params creates a new list of StreamData_serveBroadcastData_Params.
func NewStreamData_serveBroadcastData_Params_List(s *capnp.Segment, sz int32) (StreamData_serveBroadcastData_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[StreamData_serveBroadcastData_Params](l), err
}

// StreamData_serveBroadcastData_Params_Future is a wrapper for a StreamData_serveBroadcastData_Params promised by a client call.
type StreamData_serveBroadcastData_Params_Future struct{ *capnp.Future }

func (f StreamData_serveBroadcastData_Params_Future) Struct() (StreamData_serveBroadcastData_Params, error) {
	p, err := f.Future.Ptr()
	return StreamData_serveBroadcastData_Params(p.Struct()), err
}

type StreamData_serveBroadcastData_Results capnp.Struct

// StreamData_serveBroadcastData_Results_TypeID is the unique identifier for the type StreamData_serveBroadcastData_Results.
const StreamData_serveBroadcastData_Results_TypeID = 0xb728c969adbd9d92

func NewStreamData_serveBroadcastData_Results(s *capnp.Segment) (StreamData_serveBroadcastData_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StreamData_serveBroadcastData_Results(st), err
}

func NewRootStreamData_serveBroadcastData_Results(s *capnp.Segment) (StreamData_serveBroadcastData_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StreamData_serveBroadcastData_Results(st), err
}

func ReadRootStreamData_serveBroadcastData_Results(msg *capnp.Message) (StreamData_serveBroadcastData_Results, error) {
	root, err := msg.Root()
	return StreamData_serveBroadcastData_Results(root.Struct()), err
}

func (s StreamData_serveBroadcastData_Results) String() string {
	str, _ := text.Marshal(0xb728c969adbd9d92, capnp.Struct(s))
	return str
}

func (s StreamData_serveBroadcastData_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StreamData_serveBroadcastData_Results) DecodeFromPtr(p capnp.Ptr) StreamData_serveBroadcastData_Results {
	return StreamData_serveBroadcastData_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StreamData_serveBroadcastData_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StreamData_serveBroadcastData_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StreamData_serveBroadcastData_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StreamData_serveBroadcastData_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s StreamData_serveBroadcastData_Results) Payload() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s StreamData_serveBroadcastData_Results) HasPayload() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s StreamData_serveBroadcastData_Results) SetPayload(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// StreamData_serveBroadcastData_Results_List is a list of StreamData_serveBroadcastData_Results.
type StreamData_serveBroadcastData_Results_List = capnp.StructList[StreamData_serveBroadcastData_Results]

// NewStreamData_serveBroadcastData_Results creates a new list of StreamData_serveBroadcastData_Results.
func NewStreamData_serveBroadcastData_Results_List(s *capnp.Segment, sz int32) (StreamData_serveBroadcastData_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[StreamData_serveBroadcastData_Results](l), err
}

// StreamData_serveBroadcastData_Results_Future is a wrapper for a StreamData_serveBroadcastData_Results promised by a client call.
type StreamData_serveBroadcastData_Results_Future struct{ *capnp.Future }

func (f StreamData_serveBroadcastData_Results_Future) Struct() (StreamData_serveBroadcastData_Results, error) {
	p, err := f.Future.Ptr()
	return StreamData_serveBroadcastData_Results(p.Struct()), err
}

const schema_85d3acc39d94e0f8 = "x\xda\xac\x92?H\xf3P\x14\xc5\xef}/i\xfaA" +
	"\x03\xdf#Up(\x8atP\x91J)8\x08b)" +
	"up\x91\xa6:8\x09\x8f6\x83\xd8\x9a\x90\xa4B'" +
	"]\x8a\xa0[q\x12:\x08v\x11]\x04\xf1\x0f8\x09" +
	"\x16\xd7\x8a\"\x82\xe0R\xc4M7\xb7H\x0a\xb1\xe9\xa0" +
	"Pp\xbb\xc3\x8f\xdf=\x1c\xce\xffVR\x88\xcb\x83\x14" +
	"\x88\x1a\x15\x03\xce\xe3\x8dx\xb9\xfc1\xb9\x03l\x08\x01" +
	"D\x94\x00\x12%\xac\"\xa0R\xc1\x19@g\xac\xde\xbf" +
	"\xf9~\xd8\xec\x02\xea\xb8\xed\x02\xa7m@i\xcd7." +
	"\x1e\x9e\x0f\xfc\xc0=6]\xe0\xad\x0dTkW\xc7+" +
	"\xb7#g~\xe0\x1fyr\x81\x08q\x81\xd7\xf3\xc6I" +
	"X`\x0d`}\xd4\xf9|\xd9\xad]\x1f\xddU\x000" +
	"1M\x08*sD\x02Pf\xc9\x96\xb2O$\x18w" +
	"\x0cS\xb7\xf5\x89\x9c)\xea\x96\xb5\x94^\x8c\xe5\xb8\xb1" +
	"fL-\xd8\xa6\xc6\x8bin\xf3\x98\xa5\x99\xeb\x9a{" +
	"E\xb3\x9aU*\xd8h\xa9\x02\x15\x00\x04\x04`r\x0a" +
	"@\x0dRT\xc3\x047\x0c^.\xe8<\x8f2\x10\x94" +
	"\x01{Qg\xb8\xc9\x8b\x16\x80_=\xdcQK\xabZ" +
	"\x19C@0\xe4\xd3\x06~\xd5\xa6L\x9d\xe7s\xdc\xb2" +
	";\xfe\xee\xe4\x7f\xa9o7C\xed\x9e\x9b\xa1?\xfc\x80" +
	"\x0c\xa2\x1a\xa4\"\xc0\xf7`\xd0\x9b\x16\x8bg\x81\xb0Q" +
	"\x09;[Ao\x13,\xb2\x07\x84\x0dH\x8e\xd7, " +
	"O\xa2\xe3%F/2\xb5y\x123\x88_\x01\x00\x00" +
	"\xff\xff)6\xc7\xf3"

func init() {
	schemas.Register(schema_85d3acc39d94e0f8,
		0x8b36f15eba05c6d8,
		0x8bd2aaf08016a52a,
		0xa4ddd6b9c74ee513,
		0xb728c969adbd9d92,
		0xc7110414b2c7b8e7)
}
