# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import crossXDT_pb2 as crossXDT__pb2


class StreamDataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ServeData = channel.unary_stream(
                '/crossXDT.StreamData/ServeData',
                request_serializer=crossXDT__pb2.Request.SerializeToString,
                response_deserializer=crossXDT__pb2.Response.FromString,
                )
        self.ServeBroadcastData = channel.unary_stream(
                '/crossXDT.StreamData/ServeBroadcastData',
                request_serializer=crossXDT__pb2.BroadcastRequest.SerializeToString,
                response_deserializer=crossXDT__pb2.Response.FromString,
                )


class StreamDataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ServeData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServeBroadcastData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ServeData': grpc.unary_stream_rpc_method_handler(
                    servicer.ServeData,
                    request_deserializer=crossXDT__pb2.Request.FromString,
                    response_serializer=crossXDT__pb2.Response.SerializeToString,
            ),
            'ServeBroadcastData': grpc.unary_stream_rpc_method_handler(
                    servicer.ServeBroadcastData,
                    request_deserializer=crossXDT__pb2.BroadcastRequest.FromString,
                    response_serializer=crossXDT__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crossXDT.StreamData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StreamData(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ServeData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/crossXDT.StreamData/ServeData',
            crossXDT__pb2.Request.SerializeToString,
            crossXDT__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServeBroadcastData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/crossXDT.StreamData/ServeBroadcastData',
            crossXDT__pb2.BroadcastRequest.SerializeToString,
            crossXDT__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
