# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crossXDT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='crossXDT.proto',
  package='crossXDT',
  syntax='proto3',
  serialized_options=b'Z\033XDTprototype/proto/crossXDT',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x63rossXDT.proto\x12\x08\x63rossXDT\")\n\x07Request\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x11\n\tChunkSize\x18\x02 \x01(\x03\".\n\x08Response\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\x12\x13\n\x0bTotalChunks\x18\x03 \x01(\x03\x32\x44\n\nStreamData\x12\x36\n\tServeData\x12\x11.crossXDT.Request\x1a\x12.crossXDT.Response\"\x00\x30\x01\x42\x1dZ\x1bXDTprototype/proto/crossXDTb\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='crossXDT.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='crossXDT.Request.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ChunkSize', full_name='crossXDT.Request.ChunkSize', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=69,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='crossXDT.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chunk', full_name='crossXDT.Response.chunk', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TotalChunks', full_name='crossXDT.Response.TotalChunks', index=1,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'crossXDT_pb2'
  # @@protoc_insertion_point(class_scope:crossXDT.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'crossXDT_pb2'
  # @@protoc_insertion_point(class_scope:crossXDT.Response)
  })
_sym_db.RegisterMessage(Response)


DESCRIPTOR._options = None

_STREAMDATA = _descriptor.ServiceDescriptor(
  name='StreamData',
  full_name='crossXDT.StreamData',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=119,
  serialized_end=187,
  methods=[
  _descriptor.MethodDescriptor(
    name='ServeData',
    full_name='crossXDT.StreamData.ServeData',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STREAMDATA)

DESCRIPTOR.services_by_name['StreamData'] = _STREAMDATA

# @@protoc_insertion_point(module_scope)
