# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crossXDT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63rossXDT.proto\x12\x08\x63rossXDT\"\x16\n\x07Request\x12\x0b\n\x03key\x18\x01 \x01(\t\"9\n\x10\x42roadcastRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x18\n\x10\x43hunkSizeInBytes\x18\x02 \x01(\x03\".\n\x08Response\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\x12\x13\n\x0bTotalChunks\x18\x03 \x01(\x03\x32\x8e\x01\n\nStreamData\x12\x36\n\tServeData\x12\x11.crossXDT.Request\x1a\x12.crossXDT.Response\"\x00\x30\x01\x12H\n\x12ServeBroadcastData\x12\x1a.crossXDT.BroadcastRequest\x1a\x12.crossXDT.Response\"\x00\x30\x01\x42.Z,github.com/ease-lab/vhive-xdt/proto/crossXDTb\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_BROADCASTREQUEST = DESCRIPTOR.message_types_by_name['BroadcastRequest']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'crossXDT_pb2'
  # @@protoc_insertion_point(class_scope:crossXDT.Request)
  })
_sym_db.RegisterMessage(Request)

BroadcastRequest = _reflection.GeneratedProtocolMessageType('BroadcastRequest', (_message.Message,), {
  'DESCRIPTOR' : _BROADCASTREQUEST,
  '__module__' : 'crossXDT_pb2'
  # @@protoc_insertion_point(class_scope:crossXDT.BroadcastRequest)
  })
_sym_db.RegisterMessage(BroadcastRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'crossXDT_pb2'
  # @@protoc_insertion_point(class_scope:crossXDT.Response)
  })
_sym_db.RegisterMessage(Response)

_STREAMDATA = DESCRIPTOR.services_by_name['StreamData']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z,github.com/ease-lab/vhive-xdt/proto/crossXDT'
  _REQUEST._serialized_start=28
  _REQUEST._serialized_end=50
  _BROADCASTREQUEST._serialized_start=52
  _BROADCASTREQUEST._serialized_end=109
  _RESPONSE._serialized_start=111
  _RESPONSE._serialized_end=157
  _STREAMDATA._serialized_start=160
  _STREAMDATA._serialized_end=302
# @@protoc_insertion_point(module_scope)
