// Code generated by capnpc-go. DO NOT EDIT.

package crossXDT

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
	fmt "fmt"
)

type StreamData capnp.Client

// StreamData_TypeID is the unique identifier for the type StreamData.
const StreamData_TypeID = 0xc7110414b2c7b8e7

func (c StreamData) ServeData(ctx context.Context, params func(StreamData_serveData_Params) error) (StreamData_serveData_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xc7110414b2c7b8e7,
			MethodID:      0,
			InterfaceName: "crossXDT.capnp:StreamData",
			MethodName:    "serveData",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(StreamData_serveData_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return StreamData_serveData_Results_Future{Future: ans.Future()}, release
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c StreamData) String() string {
	return fmt.Sprintf("%T(%v)", c, capnp.Client(c))
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c StreamData) AddRef() StreamData {
	return StreamData(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c StreamData) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c StreamData) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c StreamData) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (StreamData) DecodeFromPtr(p capnp.Ptr) StreamData {
	return StreamData(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c StreamData) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c StreamData) IsSame(other StreamData) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c StreamData) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c StreamData) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
} // A StreamData_Server is a StreamData with a local implementation.
type StreamData_Server interface {
	ServeData(context.Context, StreamData_serveData) error
}

// StreamData_NewServer creates a new Server from an implementation of StreamData_Server.
func StreamData_NewServer(s StreamData_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(StreamData_Methods(nil, s), s, c)
}

// StreamData_ServerToClient creates a new Client from an implementation of StreamData_Server.
// The caller is responsible for calling Release on the returned Client.
func StreamData_ServerToClient(s StreamData_Server) StreamData {
	return StreamData(capnp.NewClient(StreamData_NewServer(s)))
}

// StreamData_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func StreamData_Methods(methods []server.Method, s StreamData_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 1)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc7110414b2c7b8e7,
			MethodID:      0,
			InterfaceName: "crossXDT.capnp:StreamData",
			MethodName:    "serveData",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.ServeData(ctx, StreamData_serveData{call})
		},
	})

	return methods
}

// StreamData_serveData holds the state for a server call to StreamData.serveData.
// See server.Call for documentation.
type StreamData_serveData struct {
	*server.Call
}

// Args returns the call's arguments.
func (c StreamData_serveData) Args() StreamData_serveData_Params {
	return StreamData_serveData_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c StreamData_serveData) AllocResults() (StreamData_serveData_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StreamData_serveData_Results(r), err
}

// StreamData_List is a list of StreamData.
type StreamData_List = capnp.CapList[StreamData]

// NewStreamData creates a new list of StreamData.
func NewStreamData_List(s *capnp.Segment, sz int32) (StreamData_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[StreamData](l), err
}

type StreamData_serveData_Params capnp.Struct

// StreamData_serveData_Params_TypeID is the unique identifier for the type StreamData_serveData_Params.
const StreamData_serveData_Params_TypeID = 0x8bd2aaf08016a52a

func NewStreamData_serveData_Params(s *capnp.Segment) (StreamData_serveData_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StreamData_serveData_Params(st), err
}

func NewRootStreamData_serveData_Params(s *capnp.Segment) (StreamData_serveData_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StreamData_serveData_Params(st), err
}

func ReadRootStreamData_serveData_Params(msg *capnp.Message) (StreamData_serveData_Params, error) {
	root, err := msg.Root()
	return StreamData_serveData_Params(root.Struct()), err
}

func (s StreamData_serveData_Params) String() string {
	str, _ := text.Marshal(0x8bd2aaf08016a52a, capnp.Struct(s))
	return str
}

func (s StreamData_serveData_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StreamData_serveData_Params) DecodeFromPtr(p capnp.Ptr) StreamData_serveData_Params {
	return StreamData_serveData_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StreamData_serveData_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StreamData_serveData_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StreamData_serveData_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StreamData_serveData_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s StreamData_serveData_Params) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s StreamData_serveData_Params) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s StreamData_serveData_Params) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s StreamData_serveData_Params) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// StreamData_serveData_Params_List is a list of StreamData_serveData_Params.
type StreamData_serveData_Params_List = capnp.StructList[StreamData_serveData_Params]

// NewStreamData_serveData_Params creates a new list of StreamData_serveData_Params.
func NewStreamData_serveData_Params_List(s *capnp.Segment, sz int32) (StreamData_serveData_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[StreamData_serveData_Params](l), err
}

// StreamData_serveData_Params_Future is a wrapper for a StreamData_serveData_Params promised by a client call.
type StreamData_serveData_Params_Future struct{ *capnp.Future }

func (f StreamData_serveData_Params_Future) Struct() (StreamData_serveData_Params, error) {
	p, err := f.Future.Ptr()
	return StreamData_serveData_Params(p.Struct()), err
}

type StreamData_serveData_Results capnp.Struct

// StreamData_serveData_Results_TypeID is the unique identifier for the type StreamData_serveData_Results.
const StreamData_serveData_Results_TypeID = 0x8b36f15eba05c6d8

func NewStreamData_serveData_Results(s *capnp.Segment) (StreamData_serveData_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StreamData_serveData_Results(st), err
}

func NewRootStreamData_serveData_Results(s *capnp.Segment) (StreamData_serveData_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StreamData_serveData_Results(st), err
}

func ReadRootStreamData_serveData_Results(msg *capnp.Message) (StreamData_serveData_Results, error) {
	root, err := msg.Root()
	return StreamData_serveData_Results(root.Struct()), err
}

func (s StreamData_serveData_Results) String() string {
	str, _ := text.Marshal(0x8b36f15eba05c6d8, capnp.Struct(s))
	return str
}

func (s StreamData_serveData_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StreamData_serveData_Results) DecodeFromPtr(p capnp.Ptr) StreamData_serveData_Results {
	return StreamData_serveData_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StreamData_serveData_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StreamData_serveData_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StreamData_serveData_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StreamData_serveData_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s StreamData_serveData_Results) Payload() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s StreamData_serveData_Results) HasPayload() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s StreamData_serveData_Results) SetPayload(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// StreamData_serveData_Results_List is a list of StreamData_serveData_Results.
type StreamData_serveData_Results_List = capnp.StructList[StreamData_serveData_Results]

// NewStreamData_serveData_Results creates a new list of StreamData_serveData_Results.
func NewStreamData_serveData_Results_List(s *capnp.Segment, sz int32) (StreamData_serveData_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[StreamData_serveData_Results](l), err
}

// StreamData_serveData_Results_Future is a wrapper for a StreamData_serveData_Results promised by a client call.
type StreamData_serveData_Results_Future struct{ *capnp.Future }

func (f StreamData_serveData_Results_Future) Struct() (StreamData_serveData_Results, error) {
	p, err := f.Future.Ptr()
	return StreamData_serveData_Results(p.Struct()), err
}

const schema_85d3acc39d94e0f8 = "x\xda\x12\x98\xe8\xc0b\xc8\x9b\xcf\xc4\xc0\x14(\xc3\xca" +
	"\xf6\xff\xc61\xd6]q\x1f\xcd\xba\x19\x04\xa5\x18\x19\x18" +
	"X\x19\xd9\x19\x18\x8ce\x19\x93\x18\x19\x18\x855\x19\xed" +
	"\x19\x18\xffk-\x15k\xf8\xb0\xea\x12\x8a\x02O\xc6(" +
	"\x90\x82P\xb0\x82\xe7;\x8eo\x12a\x11<\xce \xc8" +
	"\xcf\xfc\xff\xc7\x83)s\x0f\xaf\xb9\xdc\xca\xc0\xc0(\\" +
	"\xcaxI\xb8\x11\xa4^\xb8\x96\xd1]x%#;\x83" +
	"\xce\xff\xe4\xa2\xfc\xe2\xe2\x08\x97\x10\x16\xbd\xe4\xc4\x82\xbc" +
	"\x02\xab\xe0\x92\xa2\xd4\xc4\\\x97\xc4\x92D\xbd\xe2\xd4\xa2" +
	"\xb2T\x10K%(\xb5\xb8\x94=\xa7\xa48\x90\x85\x99" +
	"\x85\x81\x81\x85\x91\x81A\x90\xd7\x89\x81!\x90\x83\x991" +
	"P\x84\x89\xb1\xbe \xb12'?1\x85\x91\x97\x81\x89" +
	"\x91\x97\x81\x918C\x03\x12\x8b\x12\x99sQ\xccTB" +
	"\x98\xc9\x9e\x9dZ\xc9\xc8\xc3\xc0\xc4\xc8\x83d\x1e\x13\xba" +
	"y\x8c\x89\x01\x8c\x8c\x81,\xcc\xac\x0c\x0c\xf0pa\x84" +
	"\x85\xa0\xa0`\x10\x03\x93 '\xfb\x7f\x98\x9d\x0c\x8c\x89" +
	"\x0e\x8c\x01\x8c\x8c\x80\x00\x00\x00\xff\xff-\xc4d\x8f"

func init() {
	schemas.Register(schema_85d3acc39d94e0f8,
		0x8b36f15eba05c6d8,
		0x8bd2aaf08016a52a,
		0xc7110414b2c7b8e7)
}
