# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fnInvocation_pb2 as fnInvocation__pb2


class InvocationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RouteInvocation = channel.unary_unary(
                '/fnInvocation.Invocation/RouteInvocation',
                request_serializer=fnInvocation__pb2.InvocationRequest.SerializeToString,
                response_deserializer=fnInvocation__pb2.Empty.FromString,
                )


class InvocationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RouteInvocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InvocationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RouteInvocation': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteInvocation,
                    request_deserializer=fnInvocation__pb2.InvocationRequest.FromString,
                    response_serializer=fnInvocation__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fnInvocation.Invocation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Invocation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RouteInvocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fnInvocation.Invocation/RouteInvocation',
            fnInvocation__pb2.InvocationRequest.SerializeToString,
            fnInvocation__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
