# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import downXDT_pb2 as downXDT__pb2


class XDTtoFnStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.XDTFnCall = channel.unary_unary(
                '/downXDT.XDTtoFn/XDTFnCall',
                request_serializer=downXDT__pb2.InvocationRequest.SerializeToString,
                response_deserializer=downXDT__pb2.Empty.FromString,
                )
        self.XDTDataServe = channel.unary_stream(
                '/downXDT.XDTtoFn/XDTDataServe',
                request_serializer=downXDT__pb2.DataRequest.SerializeToString,
                response_deserializer=downXDT__pb2.Data.FromString,
                )


class XDTtoFnServicer(object):
    """Missing associated documentation comment in .proto file."""

    def XDTFnCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def XDTDataServe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_XDTtoFnServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'XDTFnCall': grpc.unary_unary_rpc_method_handler(
                    servicer.XDTFnCall,
                    request_deserializer=downXDT__pb2.InvocationRequest.FromString,
                    response_serializer=downXDT__pb2.Empty.SerializeToString,
            ),
            'XDTDataServe': grpc.unary_stream_rpc_method_handler(
                    servicer.XDTDataServe,
                    request_deserializer=downXDT__pb2.DataRequest.FromString,
                    response_serializer=downXDT__pb2.Data.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'downXDT.XDTtoFn', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class XDTtoFn(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def XDTFnCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/downXDT.XDTtoFn/XDTFnCall',
            downXDT__pb2.InvocationRequest.SerializeToString,
            downXDT__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def XDTDataServe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/downXDT.XDTtoFn/XDTDataServe',
            downXDT__pb2.DataRequest.SerializeToString,
            downXDT__pb2.Data.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
