# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: upXDT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='upXDT.proto',
  package='upXDT',
  syntax='proto3',
  serialized_options=b'Z\030XDTprototype/proto/upXDT',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bupXDT.proto\x12\x05upXDT\":\n\x07Request\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x13\n\x0bTotalChunks\x18\x03 \x01(\x03\"\x07\n\x05\x45mpty2:\n\nStreamData\x12,\n\x08SendData\x12\x0e.upXDT.Request\x1a\x0c.upXDT.Empty\"\x00(\x01\x42\x1aZ\x18XDTprototype/proto/upXDTb\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='upXDT.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chunk', full_name='upXDT.Request.chunk', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='upXDT.Request.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TotalChunks', full_name='upXDT.Request.TotalChunks', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=80,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='upXDT.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'upXDT_pb2'
  # @@protoc_insertion_point(class_scope:upXDT.Request)
  })
_sym_db.RegisterMessage(Request)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'upXDT_pb2'
  # @@protoc_insertion_point(class_scope:upXDT.Empty)
  })
_sym_db.RegisterMessage(Empty)


DESCRIPTOR._options = None

_STREAMDATA = _descriptor.ServiceDescriptor(
  name='StreamData',
  full_name='upXDT.StreamData',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=91,
  serialized_end=149,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendData',
    full_name='upXDT.StreamData.SendData',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STREAMDATA)

DESCRIPTOR.services_by_name['StreamData'] = _STREAMDATA

# @@protoc_insertion_point(module_scope)
