# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import upXDT_pb2 as upXDT__pb2


class StreamDataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendData = channel.stream_unary(
                '/upXDT.StreamData/SendData',
                request_serializer=upXDT__pb2.Request.SerializeToString,
                response_deserializer=upXDT__pb2.Empty.FromString,
                )


class StreamDataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendData(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendData': grpc.stream_unary_rpc_method_handler(
                    servicer.SendData,
                    request_deserializer=upXDT__pb2.Request.FromString,
                    response_serializer=upXDT__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'upXDT.StreamData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StreamData(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/upXDT.StreamData/SendData',
            upXDT__pb2.Request.SerializeToString,
            upXDT__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
