// Code generated by capnpc-go. DO NOT EDIT.

package downXDT

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
	fmt "fmt"
)

type XDTtoFn capnp.Client

// XDTtoFn_TypeID is the unique identifier for the type XDTtoFn.
const XDTtoFn_TypeID = 0xe2e1afe867b09fb8

func (c XDTtoFn) XDTDataServe(ctx context.Context, params func(XDTtoFn_xDTDataServe_Params) error) (XDTtoFn_xDTDataServe_Results_Future, capnp.ReleaseFunc) {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xe2e1afe867b09fb8,
			MethodID:      0,
			InterfaceName: "downXDT.capnp:XDTtoFn",
			MethodName:    "xDTDataServe",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(XDTtoFn_xDTDataServe_Params(s)) }
	}
	ans, release := capnp.Client(c).SendCall(ctx, s)
	return XDTtoFn_xDTDataServe_Results_Future{Future: ans.Future()}, release
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c XDTtoFn) String() string {
	return fmt.Sprintf("%T(%v)", c, capnp.Client(c))
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c XDTtoFn) AddRef() XDTtoFn {
	return XDTtoFn(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c XDTtoFn) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c XDTtoFn) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c XDTtoFn) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (XDTtoFn) DecodeFromPtr(p capnp.Ptr) XDTtoFn {
	return XDTtoFn(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c XDTtoFn) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c XDTtoFn) IsSame(other XDTtoFn) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c XDTtoFn) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c XDTtoFn) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
} // A XDTtoFn_Server is a XDTtoFn with a local implementation.
type XDTtoFn_Server interface {
	XDTDataServe(context.Context, XDTtoFn_xDTDataServe) error
}

// XDTtoFn_NewServer creates a new Server from an implementation of XDTtoFn_Server.
func XDTtoFn_NewServer(s XDTtoFn_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(XDTtoFn_Methods(nil, s), s, c)
}

// XDTtoFn_ServerToClient creates a new Client from an implementation of XDTtoFn_Server.
// The caller is responsible for calling Release on the returned Client.
func XDTtoFn_ServerToClient(s XDTtoFn_Server) XDTtoFn {
	return XDTtoFn(capnp.NewClient(XDTtoFn_NewServer(s)))
}

// XDTtoFn_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func XDTtoFn_Methods(methods []server.Method, s XDTtoFn_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 1)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe2e1afe867b09fb8,
			MethodID:      0,
			InterfaceName: "downXDT.capnp:XDTtoFn",
			MethodName:    "xDTDataServe",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.XDTDataServe(ctx, XDTtoFn_xDTDataServe{call})
		},
	})

	return methods
}

// XDTtoFn_xDTDataServe holds the state for a server call to XDTtoFn.xDTDataServe.
// See server.Call for documentation.
type XDTtoFn_xDTDataServe struct {
	*server.Call
}

// Args returns the call's arguments.
func (c XDTtoFn_xDTDataServe) Args() XDTtoFn_xDTDataServe_Params {
	return XDTtoFn_xDTDataServe_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c XDTtoFn_xDTDataServe) AllocResults() (XDTtoFn_xDTDataServe_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return XDTtoFn_xDTDataServe_Results(r), err
}

// XDTtoFn_List is a list of XDTtoFn.
type XDTtoFn_List = capnp.CapList[XDTtoFn]

// NewXDTtoFn creates a new list of XDTtoFn.
func NewXDTtoFn_List(s *capnp.Segment, sz int32) (XDTtoFn_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[XDTtoFn](l), err
}

type XDTtoFn_xDTDataServe_Params capnp.Struct

// XDTtoFn_xDTDataServe_Params_TypeID is the unique identifier for the type XDTtoFn_xDTDataServe_Params.
const XDTtoFn_xDTDataServe_Params_TypeID = 0x9a9747282e78c3a9

func NewXDTtoFn_xDTDataServe_Params(s *capnp.Segment) (XDTtoFn_xDTDataServe_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return XDTtoFn_xDTDataServe_Params(st), err
}

func NewRootXDTtoFn_xDTDataServe_Params(s *capnp.Segment) (XDTtoFn_xDTDataServe_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return XDTtoFn_xDTDataServe_Params(st), err
}

func ReadRootXDTtoFn_xDTDataServe_Params(msg *capnp.Message) (XDTtoFn_xDTDataServe_Params, error) {
	root, err := msg.Root()
	return XDTtoFn_xDTDataServe_Params(root.Struct()), err
}

func (s XDTtoFn_xDTDataServe_Params) String() string {
	str, _ := text.Marshal(0x9a9747282e78c3a9, capnp.Struct(s))
	return str
}

func (s XDTtoFn_xDTDataServe_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (XDTtoFn_xDTDataServe_Params) DecodeFromPtr(p capnp.Ptr) XDTtoFn_xDTDataServe_Params {
	return XDTtoFn_xDTDataServe_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s XDTtoFn_xDTDataServe_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s XDTtoFn_xDTDataServe_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s XDTtoFn_xDTDataServe_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s XDTtoFn_xDTDataServe_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s XDTtoFn_xDTDataServe_Params) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s XDTtoFn_xDTDataServe_Params) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s XDTtoFn_xDTDataServe_Params) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s XDTtoFn_xDTDataServe_Params) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// XDTtoFn_xDTDataServe_Params_List is a list of XDTtoFn_xDTDataServe_Params.
type XDTtoFn_xDTDataServe_Params_List = capnp.StructList[XDTtoFn_xDTDataServe_Params]

// NewXDTtoFn_xDTDataServe_Params creates a new list of XDTtoFn_xDTDataServe_Params.
func NewXDTtoFn_xDTDataServe_Params_List(s *capnp.Segment, sz int32) (XDTtoFn_xDTDataServe_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[XDTtoFn_xDTDataServe_Params](l), err
}

// XDTtoFn_xDTDataServe_Params_Future is a wrapper for a XDTtoFn_xDTDataServe_Params promised by a client call.
type XDTtoFn_xDTDataServe_Params_Future struct{ *capnp.Future }

func (f XDTtoFn_xDTDataServe_Params_Future) Struct() (XDTtoFn_xDTDataServe_Params, error) {
	p, err := f.Future.Ptr()
	return XDTtoFn_xDTDataServe_Params(p.Struct()), err
}

type XDTtoFn_xDTDataServe_Results capnp.Struct

// XDTtoFn_xDTDataServe_Results_TypeID is the unique identifier for the type XDTtoFn_xDTDataServe_Results.
const XDTtoFn_xDTDataServe_Results_TypeID = 0x9ab51fdb2cc4790c

func NewXDTtoFn_xDTDataServe_Results(s *capnp.Segment) (XDTtoFn_xDTDataServe_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return XDTtoFn_xDTDataServe_Results(st), err
}

func NewRootXDTtoFn_xDTDataServe_Results(s *capnp.Segment) (XDTtoFn_xDTDataServe_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return XDTtoFn_xDTDataServe_Results(st), err
}

func ReadRootXDTtoFn_xDTDataServe_Results(msg *capnp.Message) (XDTtoFn_xDTDataServe_Results, error) {
	root, err := msg.Root()
	return XDTtoFn_xDTDataServe_Results(root.Struct()), err
}

func (s XDTtoFn_xDTDataServe_Results) String() string {
	str, _ := text.Marshal(0x9ab51fdb2cc4790c, capnp.Struct(s))
	return str
}

func (s XDTtoFn_xDTDataServe_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (XDTtoFn_xDTDataServe_Results) DecodeFromPtr(p capnp.Ptr) XDTtoFn_xDTDataServe_Results {
	return XDTtoFn_xDTDataServe_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s XDTtoFn_xDTDataServe_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s XDTtoFn_xDTDataServe_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s XDTtoFn_xDTDataServe_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s XDTtoFn_xDTDataServe_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s XDTtoFn_xDTDataServe_Results) Payload() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s XDTtoFn_xDTDataServe_Results) HasPayload() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s XDTtoFn_xDTDataServe_Results) SetPayload(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// XDTtoFn_xDTDataServe_Results_List is a list of XDTtoFn_xDTDataServe_Results.
type XDTtoFn_xDTDataServe_Results_List = capnp.StructList[XDTtoFn_xDTDataServe_Results]

// NewXDTtoFn_xDTDataServe_Results creates a new list of XDTtoFn_xDTDataServe_Results.
func NewXDTtoFn_xDTDataServe_Results_List(s *capnp.Segment, sz int32) (XDTtoFn_xDTDataServe_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[XDTtoFn_xDTDataServe_Results](l), err
}

// XDTtoFn_xDTDataServe_Results_Future is a wrapper for a XDTtoFn_xDTDataServe_Results promised by a client call.
type XDTtoFn_xDTDataServe_Results_Future struct{ *capnp.Future }

func (f XDTtoFn_xDTDataServe_Results_Future) Struct() (XDTtoFn_xDTDataServe_Results, error) {
	p, err := f.Future.Ptr()
	return XDTtoFn_xDTDataServe_Results(p.Struct()), err
}

const schema_85d3acc39d94e0f8 = "x\xda\x12\x98\xe0\xc0b\xc8\x9b\xcf\xc4\xc0\x14(\xc3\xca" +
	"\xf6\x7f\xe5\xe1\x0a=\x0d\xf7\xe9\xb3\x18\x04\xc5\x18\x19\x18" +
	"X\x19\xd9\x19\x18\x8ce\x19\x83\x18\x19\x18\x855\x19\xed" +
	"\x19\x18\xff\xf3T\x1e\xd1\xb9-\xbf\x15E\x81'c\x14" +
	"HA(X\xc1\x8e\xf9\x1b\xd2_\xac\x7f\xf8\x88A\x90" +
	"\x8f\xf9\xff\x8f\x07S\xe6\x1e^s\xb9\x95\x81\x81Q\xb8" +
	"\x94q\x93p-H\xbdp%\xa3\xbb\xf0RFv\x06" +
	"\x9d\xff)\xf9\xe5y\x11.!z,\xc9\x89\x05y\x05" +
	"V\x11.!%\xf9nyz\x15.!.\x89%\x89" +
	"\xc1\xa9Ee\xa9*\x01\x89E\x89\xb9\x8c\xc5\x81,\xcc" +
	",\x0c\x0c,\x8c\x0c\x0c\x82\xbcJ\x0c\x0c\x81\x1c\xcc\x8c" +
	"\x81\"L\x8c\xec\xd9\xa9\x95\x8c<\x0cL\x8c<\x0c\x8c" +
	"D\x19\x17\x94Z\\\x9a\xc3\\\x82b\x9e\x13\xc2\xbc\xfa" +
	"\x82\xc4\xca\x9c\xfc\xc4\x14F^\x06&F^$3\x19" +
	"af\xca\x83\x0d\x0d`d\x0cdafe`\x80\x07" +
	"\x19#,h\x04\x05\xb3\x18\x98\x049\xd9\xff\xc3\xece" +
	"\xe0\x07\xd9\xec\xc0\x18\xc0\xc8\x08\x08\x00\x00\xff\xff/\x09" +
	"`\xf1"

func init() {
	schemas.Register(schema_85d3acc39d94e0f8,
		0x9a9747282e78c3a9,
		0x9ab51fdb2cc4790c,
		0xe2e1afe867b09fb8)
}
