# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: downXDT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdownXDT.proto\x12\x07\x64ownXDT\"$\n\x11InvocationRequest\x12\x0f\n\x07XDTJSON\x18\x01 \x01(\x0c\"1\n\x12InvocationResponse\x12\x0f\n\x07message\x18\x01 \x01(\x0c\x12\n\n\x02ok\x18\x02 \x01(\x08\"\x07\n\x05\x45mpty\"*\n\x04\x44\x61ta\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\x12\x13\n\x0bTotalChunks\x18\x03 \x01(\x03\"\x1a\n\x0b\x44\x61taRequest\x12\x0b\n\x03key\x18\x01 \x01(\t2\x8a\x01\n\x07XDTtoFn\x12\x46\n\tXDTFnCall\x12\x1a.downXDT.InvocationRequest\x1a\x1b.downXDT.InvocationResponse\"\x00\x12\x37\n\x0cXDTDataServe\x12\x14.downXDT.DataRequest\x1a\r.downXDT.Data\"\x00\x30\x01\x42-Z+github.com/ease-lab/vhive-xdt/proto/downXDTb\x06proto3')



_INVOCATIONREQUEST = DESCRIPTOR.message_types_by_name['InvocationRequest']
_INVOCATIONRESPONSE = DESCRIPTOR.message_types_by_name['InvocationResponse']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_DATA = DESCRIPTOR.message_types_by_name['Data']
_DATAREQUEST = DESCRIPTOR.message_types_by_name['DataRequest']
InvocationRequest = _reflection.GeneratedProtocolMessageType('InvocationRequest', (_message.Message,), {
  'DESCRIPTOR' : _INVOCATIONREQUEST,
  '__module__' : 'downXDT_pb2'
  # @@protoc_insertion_point(class_scope:downXDT.InvocationRequest)
  })
_sym_db.RegisterMessage(InvocationRequest)

InvocationResponse = _reflection.GeneratedProtocolMessageType('InvocationResponse', (_message.Message,), {
  'DESCRIPTOR' : _INVOCATIONRESPONSE,
  '__module__' : 'downXDT_pb2'
  # @@protoc_insertion_point(class_scope:downXDT.InvocationResponse)
  })
_sym_db.RegisterMessage(InvocationResponse)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'downXDT_pb2'
  # @@protoc_insertion_point(class_scope:downXDT.Empty)
  })
_sym_db.RegisterMessage(Empty)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'downXDT_pb2'
  # @@protoc_insertion_point(class_scope:downXDT.Data)
  })
_sym_db.RegisterMessage(Data)

DataRequest = _reflection.GeneratedProtocolMessageType('DataRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATAREQUEST,
  '__module__' : 'downXDT_pb2'
  # @@protoc_insertion_point(class_scope:downXDT.DataRequest)
  })
_sym_db.RegisterMessage(DataRequest)

_XDTTOFN = DESCRIPTOR.services_by_name['XDTtoFn']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z+github.com/ease-lab/vhive-xdt/proto/downXDT'
  _INVOCATIONREQUEST._serialized_start=26
  _INVOCATIONREQUEST._serialized_end=62
  _INVOCATIONRESPONSE._serialized_start=64
  _INVOCATIONRESPONSE._serialized_end=113
  _EMPTY._serialized_start=115
  _EMPTY._serialized_end=122
  _DATA._serialized_start=124
  _DATA._serialized_end=166
  _DATAREQUEST._serialized_start=168
  _DATAREQUEST._serialized_end=194
  _XDTTOFN._serialized_start=197
  _XDTTOFN._serialized_end=335
# @@protoc_insertion_point(module_scope)
