# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: upXDT.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bupXDT.proto\x12\x05upXDT\":\n\x07Request\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x13\n\x0bTotalChunks\x18\x03 \x01(\x03\"\x07\n\x05\x45mpty2o\n\nStreamData\x12,\n\x08SendData\x12\x0e.upXDT.Request\x1a\x0c.upXDT.Empty\"\x00(\x01\x12\x33\n\x0f\x42roadcastUpload\x12\x0e.upXDT.Request\x1a\x0c.upXDT.Empty\"\x00(\x01\x42+Z)github.com/ease-lab/vhive-xdt/proto/upXDTb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'upXDT_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z)github.com/ease-lab/vhive-xdt/proto/upXDT'
  _REQUEST._serialized_start=22
  _REQUEST._serialized_end=80
  _EMPTY._serialized_start=82
  _EMPTY._serialized_end=89
  _STREAMDATA._serialized_start=91
  _STREAMDATA._serialized_end=202
# @@protoc_insertion_point(module_scope)
