apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fx
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/vhiveease/fx:latest
          imagePullPolicy: Always
          env:
            - name: CHUNK_SIZE_IN_BYTES
              value: "65536"
            - name: CT_BUFFER_SIZE
              value: "25"
            - name: NUMBER_OF_BUFFERS
              value: "2"
            - name: ST_AND_FW_BUFFER_SIZE
              value: "1600"
            - name: ROUTING
              value: "false"
            - name: TRACING_ENABLED
              value: "1000"
            - name: RPC_TIMEOUT_MAX_BACK_OFF
              value: "60000"
            - name: RPC_TIMEOUT_DURATION
              value: "1"
            - name: RPC_RETRY_DELAY
              value: "10"
          ports:
            - name: h2c
              containerPort: 50010