// control path request

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.7
// source: QPToDstFn.proto

package QPToDstFnProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XdtJson []byte `protobuf:"bytes,1,opt,name=xdt_json,json=xdtJson,proto3" json:"xdt_json,omitempty"`
}

func (x *InvocationRequest) Reset() {
	*x = InvocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_QPToDstFn_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationRequest) ProtoMessage() {}

func (x *InvocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_QPToDstFn_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationRequest.ProtoReflect.Descriptor instead.
func (*InvocationRequest) Descriptor() ([]byte, []int) {
	return file_QPToDstFn_proto_rawDescGZIP(), []int{0}
}

func (x *InvocationRequest) GetXdtJson() []byte {
	if x != nil {
		return x.XdtJson
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_QPToDstFn_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_QPToDstFn_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_QPToDstFn_proto_rawDescGZIP(), []int{1}
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_QPToDstFn_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_QPToDstFn_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_QPToDstFn_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type DataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ChunkSize int64  `protobuf:"varint,65536,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_QPToDstFn_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_QPToDstFn_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_QPToDstFn_proto_rawDescGZIP(), []int{3}
}

func (x *DataRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DataRequest) GetChunkSize() int64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

var File_QPToDstFn_proto protoreflect.FileDescriptor

var file_QPToDstFn_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x51, 0x50, 0x54, 0x6f, 0x44, 0x73, 0x74, 0x46, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x51, 0x50, 0x54, 0x6f, 0x44, 0x73, 0x74, 0x46, 0x6e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x2e, 0x0a, 0x11, 0x49, 0x6e, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x78, 0x64, 0x74, 0x5f, 0x6a, 0x73,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x78, 0x64, 0x74, 0x4a, 0x73, 0x6f,
	0x6e, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x1c, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x40, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0a, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x80, 0x80, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x32, 0x99, 0x01, 0x0a, 0x07, 0x58,
	0x44, 0x54, 0x74, 0x6f, 0x46, 0x6e, 0x12, 0x47, 0x0a, 0x09, 0x58, 0x44, 0x54, 0x46, 0x6e, 0x43,
	0x61, 0x6c, 0x6c, 0x12, 0x21, 0x2e, 0x51, 0x50, 0x54, 0x6f, 0x44, 0x73, 0x74, 0x46, 0x6e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x51, 0x50, 0x54, 0x6f, 0x44, 0x73, 0x74,
	0x46, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x45, 0x0a, 0x0c, 0x58, 0x44, 0x54, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x12,
	0x1b, 0x2e, 0x51, 0x50, 0x54, 0x6f, 0x44, 0x73, 0x74, 0x46, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x51,
	0x50, 0x54, 0x6f, 0x44, 0x73, 0x74, 0x46, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x00, 0x30, 0x01, 0x42, 0x4b, 0x5a, 0x49, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x61, 0x73, 0x65, 0x2d, 0x6c, 0x61, 0x62, 0x2f, 0x76, 0x68,
	0x69, 0x76, 0x65, 0x5f, 0x73, 0x74, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x2f, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x51, 0x50, 0x54, 0x6f, 0x44, 0x73, 0x74, 0x46, 0x6e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_QPToDstFn_proto_rawDescOnce sync.Once
	file_QPToDstFn_proto_rawDescData = file_QPToDstFn_proto_rawDesc
)

func file_QPToDstFn_proto_rawDescGZIP() []byte {
	file_QPToDstFn_proto_rawDescOnce.Do(func() {
		file_QPToDstFn_proto_rawDescData = protoimpl.X.CompressGZIP(file_QPToDstFn_proto_rawDescData)
	})
	return file_QPToDstFn_proto_rawDescData
}

var file_QPToDstFn_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_QPToDstFn_proto_goTypes = []interface{}{
	(*InvocationRequest)(nil), // 0: QPToDstFnProto.InvocationRequest
	(*Empty)(nil),             // 1: QPToDstFnProto.Empty
	(*Data)(nil),              // 2: QPToDstFnProto.Data
	(*DataRequest)(nil),       // 3: QPToDstFnProto.DataRequest
}
var file_QPToDstFn_proto_depIdxs = []int32{
	0, // 0: QPToDstFnProto.XDTtoFn.XDTFnCall:input_type -> QPToDstFnProto.InvocationRequest
	3, // 1: QPToDstFnProto.XDTtoFn.XDTDataServe:input_type -> QPToDstFnProto.DataRequest
	1, // 2: QPToDstFnProto.XDTtoFn.XDTFnCall:output_type -> QPToDstFnProto.Empty
	2, // 3: QPToDstFnProto.XDTtoFn.XDTDataServe:output_type -> QPToDstFnProto.Data
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_QPToDstFn_proto_init() }
func file_QPToDstFn_proto_init() {
	if File_QPToDstFn_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_QPToDstFn_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_QPToDstFn_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_QPToDstFn_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_QPToDstFn_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_QPToDstFn_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_QPToDstFn_proto_goTypes,
		DependencyIndexes: file_QPToDstFn_proto_depIdxs,
		MessageInfos:      file_QPToDstFn_proto_msgTypes,
	}.Build()
	File_QPToDstFn_proto = out.File
	file_QPToDstFn_proto_rawDesc = nil
	file_QPToDstFn_proto_goTypes = nil
	file_QPToDstFn_proto_depIdxs = nil
}
