# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fnInvocation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fnInvocation.proto',
  package='fnInvocation',
  syntax='proto3',
  serialized_options=b'Z*github.com/ease-lab/xdt/proto/fnInvocation',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x66nInvocation.proto\x12\x0c\x66nInvocation\"5\n\x11InvocationRequest\x12\x0f\n\x07XDTJSON\x18\x01 \x01(\x0c\x12\x0f\n\x07SQPAddr\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2W\n\nInvocation\x12I\n\x0fRouteInvocation\x12\x1f.fnInvocation.InvocationRequest\x1a\x13.fnInvocation.Empty\"\x00\x42,Z*github.com/ease-lab/xdt/proto/fnInvocationb\x06proto3'
)




_INVOCATIONREQUEST = _descriptor.Descriptor(
  name='InvocationRequest',
  full_name='fnInvocation.InvocationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='XDTJSON', full_name='fnInvocation.InvocationRequest.XDTJSON', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SQPAddr', full_name='fnInvocation.InvocationRequest.SQPAddr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=89,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='fnInvocation.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['InvocationRequest'] = _INVOCATIONREQUEST
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InvocationRequest = _reflection.GeneratedProtocolMessageType('InvocationRequest', (_message.Message,), {
  'DESCRIPTOR' : _INVOCATIONREQUEST,
  '__module__' : 'fnInvocation_pb2'
  # @@protoc_insertion_point(class_scope:fnInvocation.InvocationRequest)
  })
_sym_db.RegisterMessage(InvocationRequest)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'fnInvocation_pb2'
  # @@protoc_insertion_point(class_scope:fnInvocation.Empty)
  })
_sym_db.RegisterMessage(Empty)


DESCRIPTOR._options = None

_INVOCATION = _descriptor.ServiceDescriptor(
  name='Invocation',
  full_name='fnInvocation.Invocation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=100,
  serialized_end=187,
  methods=[
  _descriptor.MethodDescriptor(
    name='RouteInvocation',
    full_name='fnInvocation.Invocation.RouteInvocation',
    index=0,
    containing_service=None,
    input_type=_INVOCATIONREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INVOCATION)

DESCRIPTOR.services_by_name['Invocation'] = _INVOCATION

# @@protoc_insertion_point(module_scope)
