// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package SrcFnToQPProto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StreamDataClient is the client API for StreamData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamDataClient interface {
	CollectData(ctx context.Context, opts ...grpc.CallOption) (StreamData_CollectDataClient, error)
}

type streamDataClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamDataClient(cc grpc.ClientConnInterface) StreamDataClient {
	return &streamDataClient{cc}
}

func (c *streamDataClient) CollectData(ctx context.Context, opts ...grpc.CallOption) (StreamData_CollectDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamData_ServiceDesc.Streams[0], "/SrcFnToQPProto.StreamData/CollectData", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamDataCollectDataClient{stream}
	return x, nil
}

type StreamData_CollectDataClient interface {
	Send(*Request) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type streamDataCollectDataClient struct {
	grpc.ClientStream
}

func (x *streamDataCollectDataClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamDataCollectDataClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamDataServer is the server API for StreamData service.
// All implementations must embed UnimplementedStreamDataServer
// for forward compatibility
type StreamDataServer interface {
	CollectData(StreamData_CollectDataServer) error
	mustEmbedUnimplementedStreamDataServer()
}

// UnimplementedStreamDataServer must be embedded to have forward compatible implementations.
type UnimplementedStreamDataServer struct {
}

func (UnimplementedStreamDataServer) CollectData(StreamData_CollectDataServer) error {
	return status.Errorf(codes.Unimplemented, "method CollectData not implemented")
}
func (UnimplementedStreamDataServer) mustEmbedUnimplementedStreamDataServer() {}

// UnsafeStreamDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamDataServer will
// result in compilation errors.
type UnsafeStreamDataServer interface {
	mustEmbedUnimplementedStreamDataServer()
}

func RegisterStreamDataServer(s grpc.ServiceRegistrar, srv StreamDataServer) {
	s.RegisterService(&StreamData_ServiceDesc, srv)
}

func _StreamData_CollectData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamDataServer).CollectData(&streamDataCollectDataServer{stream})
}

type StreamData_CollectDataServer interface {
	SendAndClose(*Empty) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type streamDataCollectDataServer struct {
	grpc.ServerStream
}

func (x *streamDataCollectDataServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamDataCollectDataServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamData_ServiceDesc is the grpc.ServiceDesc for StreamData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SrcFnToQPProto.StreamData",
	HandlerType: (*StreamDataServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CollectData",
			Handler:       _StreamData_CollectData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "SrcFnToQP.proto",
}
