name: XDT tests

on:
  push:
    branches: [ main ]
    paths:
      - 'examples/prototype/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'examples/prototype/**'
  workflow_dispatch:

env:
  GOOS: linux
  GO111MODULE: on

jobs:
  Test:
    name: Test
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        test-type: [unit, integ]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run test
      run: cd examples/prototype && make ${{ matrix.test-type }}-test
