name: XDT tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  workflow_dispatch:

env:
  GOOS: linux
  GO111MODULE: on

jobs:
  Test:
    name: Test
    runs-on: [self-hosted]
    strategy:
      fail-fast: false
      matrix:
        test-type: [unit, integ, timeout, parallel-invoke, fan-in, fan-out, get-put]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run test
      run: make ${{ matrix.test-type }}-test
  
  CodeLint:
    name: Test Code quality
    runs-on: [self-hosted]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Check sdk code
        if: ${{ always() }}
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: sdk/golang
          args: --timeout 5m
      - name: Check dQP code
        if: ${{ always() }}
        env:
          DIR: queue-proxy/dQP
        run: cd $DIR && golangci-lint run --out-format=github-actions --path-prefix=$DIR --timeout 5m
      - name: Check plotter code
        if: ${{ always() }}
        env:
          DIR: plotter
        run: cd $DIR && golangci-lint run --out-format=github-actions --path-prefix=$DIR --timeout 5m
      - name: Check sQP code
        if: ${{ always() }}
        env:
          DIR: queue-proxy/sQP
        run: cd $DIR && golangci-lint run --out-format=github-actions --path-prefix=$DIR --timeout 5m
      - name: Check user-functions/fx code
        if: ${{ always() }}
        env:
          DIR: user-functions/fx
        run: cd $DIR && golangci-lint run --out-format=github-actions --path-prefix=$DIR --timeout 5m
      - name: Check user-functions/gx code
        if: ${{ always() }}
        env:
          DIR: user-functions/gx
        run: cd $DIR && golangci-lint run --out-format=github-actions --path-prefix=$DIR --timeout 5m
      - name: Check user-functions/dQP code
        if: ${{ always() }}
        env:
          DIR: user-functions/dQP
        run: cd $DIR && golangci-lint run --out-format=github-actions --path-prefix=$DIR --timeout 5m
      - name: Check user-functions/sQP code
        if: ${{ always() }}
        env:
          DIR: user-functions/sQP
        run: cd $DIR && golangci-lint run --out-format=github-actions --path-prefix=$DIR --timeout 5m
  Benchmark:
    name: Benchmark XDT
    runs-on: [self-hosted]
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Run benchmarks
        run: make benchmark-XDT
      - name: Archive log artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: XDT benchmarks
          path: |
            tests/*.png

  Python-SDK-Test:
    name: Python SDK Test
    runs-on: [ self-hosted ]
    strategy:
      fail-fast: false
      matrix:
        test-type: [ unit, integ, timeout, get-put]
        python-version: [3.7, 3.8, 3.9]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install fuser
        run: sudo apt-get install psmisc
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: install environs package
        run: pip install environs --user
      - name: Run test
        run: make python-${{ matrix.test-type }}-test